# version: '3.8'
services:
  # 1. Base de Datos
  postgres_db:
    image: postgres:16-alpine
    container_name: payroll_postgres
    environment:
      POSTGRES_USER: payroll_user
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: payroll_db
    ports:
      - "5432:5432" # Puerto externo : Puerto interno
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos
    networks:
      - payroll-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payroll_user -d payroll_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Cola de Mensajería (RabbitMQ)
  rabbitmq_broker:
    image: rabbitmq:3-management-alpine
    container_name: payroll_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Protocolo AMQP (para tu app Java)
      - "15672:15672" # Panel de Administración Web (http://localhost:15672)
    networks:
      - payroll-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  # 3. Tu Aplicación (Payroll Engine)
  payroll_app:
    build: . # Usa el Dockerfile del directorio actual
    container_name: payroll_engine
    ports:
      - "8080:8080"
    environment:
      # Conectamos usando los nombres de servicio definidos arriba
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/payroll_db
      SPRING_DATASOURCE_USERNAME: payroll_user
      SPRING_DATASOURCE_PASSWORD: secret_password
      SPRING_RABBITMQ_HOST: rabbitmq_broker
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      postgres_db:
        condition: service_healthy
      rabbitmq_broker:
        condition: service_healthy
    networks:
      - payroll-net
    restart: on-failure

# Definición de volúmenes y redes
volumes:
  postgres_data:

networks:
  payroll-net:
    driver: bridge
