# version: '3.8'
services:
  # 1. Base de Datos
  postgres_db:
    image: postgres:16-alpine
    container_name: payroll_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432" # Puerto externo : Puerto interno
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistencia de datos
    networks:
      - payroll-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Cola de Mensajería (RabbitMQ)
  rabbitmq_broker:
    image: rabbitmq:3-management-alpine
    container_name: payroll_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"   # Protocolo AMQP (para tu app Java)
      - "${RABBITMQ_MANAGEMENT_PORT}:15672" # Panel de Administración Web (http://localhost:15672)
    networks:
      - payroll-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  # 3. Tu Aplicación (Payroll Engine)
  payroll_app:
    build: . # Usa el Dockerfile del directorio actual
    container_name: payroll_engine
    ports:
      - "${APP_PORT}:8080"
      - "${DEBUG_PORT}:5005" # <--- PUERTO DE DEBUG (Exponerlo es vital)
    environment:
      # Conectamos usando los nombres de servicio definidos arriba
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq_broker
      SPRING_RABBITMQ_PORT: 5672
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
    depends_on:
      postgres_db:
        condition: service_healthy
      rabbitmq_broker:
        condition: service_healthy
    networks:
      - payroll-net
    restart: on-failure

# Definición de volúmenes y redes
volumes:
  postgres_data:

networks:
  payroll-net:
    driver: bridge
